name = "OptimizationMod"
uuid = "a6e1edab-866f-428e-9e49-d95cc74eeab6"
authors = ["Roy Tseng <tseng17@gapp.nthu.edu.tw>"]
version = "0.1.0"

[deps]
IntervalMod = "989ec101-f764-4c86-912d-7a4c128ad82a"
ResourceMod = "a44a16ad-e498-4b0b-8ad9-2606a38d101a"
